apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-demo
  name: springboot-demo
spec:
  ports:
    - name: springboot-demo
      port: 8080
      protocol: TCP
  selector:
    app: springboot-demo
  type: LoadBalancer