apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-demo-deployment2
  labels:
    app: docker-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-demo
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
      - name: docker-k8s-demo
        image: neozhixuan/springboot-k8s.jar
        ports:
        - containerPort: 8080
          protocol: TCP
